<a href="https://colab.research.google.com/github/Ansh3931up/DS-Course_Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a fundamental package for scientific computing

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
l=[1,2,3,4,"arrrya"]
arr=np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim
arr1=np.array([[1,2,3],[4,5,6]])
arr1.ndim

2

In [11]:
mat=np.matrix([1,3,4,4])
type(mat)

numpy.matrix

In [15]:
# more ways to convert to array
l=[1,2,3]
print(np.asarray(l))
print(np.asanyarray([1,2,3]))


[1 2 3]
[1 2 3]


The numpy.array, numpy.asarray, and numpy.asanyarray functions are used to create arrays in NumPy, but they have different use cases and behavior:

1. numpy.array
Creates a new array from any object (list, tuple, or another array).
By default, it always copies the data, creating a new array.
You can specify additional parameters like dtype, order, and ndmin.
Use when you need a new copy of the array.

2. numpy.asarray
Similar to numpy.array but with one main difference: it does not copy the data if the input is already an array of the specified dtype.
Use when you want to convert a list or other sequence into an array but do not want to copy if it is already an array.
It ensures the object is converted to an array only if it isn’t one already.

3. numpy.asanyarray
Similar to numpy.asarray but with one difference: it preserves the subclass of the input array, such as matrix or masked array.
If the input is already a subclass of ndarray, it does not convert it to a base ndarray.
Use this function when you want to work with arrays but want to ensure the input remains in its original subclass.

Summary:
numpy.array: Always creates a new array and copies the data.
numpy.asarray: Converts the input to an array, avoiding copies if the input is already an array.
numpy.asanyarray: Similar to asarray but preserves subclasses, useful for preserving matrix or masked array types.
Choose based on whether you need a new array, want to avoid copying, or want to preserve the array's type.

In [17]:
t=((2,3,2),(4,5,6))
arr=np.array(t)
arr

array([[2, 3, 2],
       [4, 5, 6]])

In [18]:
a=arr
a # shallow copy
b=arr.copy() # deep copy
b

array([[2, 3, 2],
       [4, 5, 6]])

In [22]:
# from function
arr2=np.fromfunction(lambda i,j:i==j,(3,3))

In [24]:
arr2.shape

(3, 3)

In [25]:
arr2.size

9

In [26]:
# iterator
# np.fromiter(iterator,int)
np.fromiter([i for i in range(5)],dtype=int)

array([0, 1, 2, 3, 4])

In [27]:
np.fromstring('22 23 24',sep=" ")

array([22., 23., 24.])

In [28]:
np.array("ansh,vansh,heros,brother".split(','))

array(['ansh', 'vansh', 'heros', 'brother'], dtype='<U7')

Numpy Advance 01

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros(6,int)

array([0, 0, 0, 0, 0, 0])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
b=np.zeros((1,3,4))

In [38]:
b=b+5
b*10

array([[[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]]])

In [43]:
np.eye(5) # return a identity matrix ,return a 2D array with ones on diagonal and zeros elsewhere

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
import random
random.choice((1,2,3,4))
random.choice("ajadgs")

'a'

In [48]:
random.randrange(1,10)

9

In [49]:
random.random() # generate between 0 and 1

0.6552442336584392

In [55]:
l=[1,2,3,4,5]
random.shuffle(l)
l

[2, 3, 1, 5, 4]

In [56]:
random.uniform(7,14)

11.626028565898007

In [61]:
np.random.random_sample((5,4))

array([[0.98429225, 0.3323554 , 0.30910802, 0.25712834],
       [0.34986561, 0.12762765, 0.44133117, 0.49716597],
       [0.61882853, 0.09198089, 0.41864387, 0.39986698],
       [0.04330335, 0.46582914, 0.22862976, 0.55947316],
       [0.67007875, 0.3438271 , 0.74481238, 0.7857656 ]])

In [63]:
np.random.randn()

2.249160312285677

In [73]:
a1=np.random.randint(1,5,(4,4),int)
a1

array([[4, 2, 2, 3],
       [2, 3, 2, 1],
       [2, 4, 1, 1],
       [1, 1, 3, 1]])

In [76]:
a1.reshape(2,8)

array([[4, 2, 2, 3, 2, 3, 2, 1],
       [2, 4, 1, 1, 1, 1, 3, 1]])

In [77]:
a1.reshape(16,-1)

array([[4],
       [2],
       [2],
       [3],
       [2],
       [3],
       [2],
       [1],
       [2],
       [4],
       [1],
       [1],
       [1],
       [1],
       [3],
       [1]])

In [78]:
a1.reshape(2,2,4)

array([[[4, 2, 2, 3],
        [2, 3, 2, 1]],

       [[2, 4, 1, 1],
        [1, 1, 3, 1]]])

In [83]:
a1[a1>3]
a1[0][0]=1
a1

array([[1, 2, 2, 3],
       [2, 3, 2, 1],
       [2, 4, 1, 1],
       [1, 1, 3, 1]])

In [94]:
a1[0:3,[0,1,2,3]]

array([[1, 2, 2, 3],
       [2, 3, 2, 1],
       [2, 4, 1, 1]])

In [95]:
a1*a1

array([[ 1,  4,  4,  9],
       [ 4,  9,  4,  1],
       [ 4, 16,  1,  1],
       [ 1,  1,  9,  1]])

In [96]:
a1/a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
b=a1@a1
b

array([[12, 19, 17, 10],
       [13, 22, 15, 12],
       [13, 21, 16, 12],
       [10, 18, 10,  8]])

In [99]:
b.T

array([[12, 13, 13, 10],
       [19, 22, 21, 18],
       [17, 15, 16, 10],
       [10, 12, 12,  8]])

Numpy Advance 03

In [100]:
import numpy as np

In [102]:
arr1=np.random.randint(1,3,(3,3))
arr1

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [103]:
arr1.flatten()

array([1, 1, 1, 2, 1, 1, 1, 2, 1])

In [104]:
arr1.ndim

2

In [108]:
np.expand_dims(arr1,axis=0)

array([[[1, 1, 1],
        [2, 1, 1],
        [1, 2, 1]]])

In [110]:
np.squeeze(arr1)

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [111]:
np.repeat(arr1,4)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1])

In [114]:
np.roll(arr1,3)#shift place

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [115]:
d=np.array(["pw","skills"])
np.char.upper(d)
np.char.capitalize(d)


array(['Pw', 'Skills'], dtype='<U6')

In [116]:
np.sin(arr1)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.84147098],
       [0.84147098, 0.90929743, 0.84147098]])

In [117]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231,  0.54030231],
       [-0.41614684,  0.54030231,  0.54030231],
       [ 0.54030231, -0.41614684,  0.54030231]])

In [118]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772,  1.55740772],
       [ 1.55740772, -2.18503986,  1.55740772]])

In [119]:
np.log10(arr1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.     ]])

In [120]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [121]:
np.power(arr1,3)

array([[1, 1, 1],
       [8, 1, 1],
       [1, 8, 1]])

In [122]:
np.max(arr1)

2

In [123]:
np.mean(arr1)

1.2222222222222223

In [124]:
np.min(arr1)

1

In [125]:
np.std(arr1)

0.41573970964154905

In [126]:
np.var(arr1)

0.1728395061728395

In [127]:
np.subtract(arr1,arr2)

array([[0, 1, 1],
       [2, 0, 1],
       [1, 2, 0]])

In [128]:
np.multiply(arr1,arr2)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [129]:
np.mod(arr1,arr2)# return element wise remaninder

<ipython-input-129-155d034b9e0b>:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(arr1,arr2)# return element wise remaninder


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [130]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [131]:
e=np.array([5,6,7,8,9,1,2,3])
np.sort(e)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [132]:
np.searchsorted(e,9)

4

In [133]:
np.count_nonzero(e)

8

In [135]:
e[e>5]

array([6, 7, 8, 9])

In [137]:
np.where(e>5)

(array([1, 2, 3, 4]),)

In [138]:
np.extract(e>5,e)

array([6, 7, 8, 9])

In [139]:
e.byteswap()

array([360287970189639680, 432345564227567616, 504403158265495552,
       576460752303423488, 648518346341351424,  72057594037927936,
       144115188075855872, 216172782113783808])

In [140]:
np.linalg.det(arr1)

1.0

In [141]:
np.linalg.inv(arr1)#inverse only valid if determinant of the array is not 0

array([[-1.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [-1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -1.00000000e+00, -1.00000000e+00]])

In [142]:
np.linalg.solve(arr1,arr2)

array([[-1.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [-1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -1.00000000e+00, -1.00000000e+00]])